### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by pablomaurer** [jjdltc/jjdltc-cordova-plugin-sftp#1]
Hey thanks for sharing. Opening this issue, to track ios support.

**Comment by jjdltc** [comment]
And after many yers... I push a partial [support](https://github.com/jjdltc/jjdltc-cordova-plugin-sftp/tree/dev/ios) for iOS. It's functional / works to make downloads. Few more reviews and I will merge with master, and finally close this issue :)

**Comment by pablomaurer** [comment]
Ha! 😆

**Comment by jjdltc** [comment]
Well, 3 years is better than never :).
Already in master
