### ISSUE TITLE
Events fail due to CSP errors

### ISSUE THREAD

**Issue by orgicus** [jjdltc/jjdltc-cordova-plugin-sftp#2]
Currently, uncaught errors like this one are thrown:
```javascript
cordova.js:1070 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src *".
```

This breaks the event listeners, which no longer fire even though they're added to the document.

**Comment by jjdltc** [comment]
Long time not update here, but if you (@orgicus) could be more specific about the issue I could check and patch / update, please, tell me:
- What were you doing when the error happened
- What cordova version are you running
- Does it fail always or just in specific flows

**Comment by orgicus** [comment]
Hi,

The details are:

- I was calling `download()` on a `JJsftp` instance
- I am using Cordova version 6.3.1
- It shows the errors when downloading: during download start/progress and end. once the download is done (no events have attempted to dispatch), the errors stop

If it helps, the app is compiled with the default Cordova generated config.xml.
I just added the android write permission to AndroidManifest.xml:

```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Thank you for taking your time to look into this.
Let me know if there are any other details that may help.

**Comment by jjdltc** [comment]
Since recent update (Jan 2019) I can't reproduce this.
I'm sorry for the delay, i'm closing the issue as inactive (Blame me :/)
If still occurs, re-open a new one and I will look in the problem
